---
title: "Untitled"
output: html_document
date: "2024-09-30"
---
```{r}
validity.Parzen.smoother <- function(object) {
   
    if (length(object@Data) == 0) { return("Data set is empty")} #this one works 

    if (object@h == 0) {return("h is zero")}  #this works
   
  return(TRUE)
  
}

setClass("Parzen.smoother",representation(Data = "numeric",
                                    h = "numeric",
                                    Probs = "numeric",
                                    input = "numeric"), validity = validity.Parzen.smoother, 
                                    prototype = list(h = NA_real_))
                                 
setMethod("initialize", "Parzen.smoother", function(.Object, Data, h = NA_real_, Probs, input) {
  Data <- na.omit(Data)
  
  output <- numeric(length(Data)) #cleaning up the na's works 
  
   if (is.na(h)) {
    s <- sd(Data)
    inter_q <- IQR(Data)
    n <- length(Data)
    h <- 1.06 * min(s, inter_q / 1.249) * n^(-1/5)
   }
    .Object <- callNextMethod(.Object, Data = Data, h = h, Probs = Probs, input=input)
  
  # Validate the object
  validObject(.Object)
  
  return(.Object)
  
})

```



```{r}
setGeneric("Parzen.creator", function(object) {standadardGeneric("Parzen.creator")})

setMethod("Parzen.creator", signature= "Parzen.smoother", function(object){
  
  n <- length(object@Data)
  
  k <- length(object@input)
  
  for (j in 1:k) {
      
      for (i in 1:n) {
          
        object@Probs[j] = sum(1/object@h*mean(dnorm((object@Data[i]-object@input[j])/object@h)))
         }
     }
  return(object)
})

```


in case they ask specifically for an overloaded show function
```{r}
setGeneric("demonstrate", function(object) {standadardGeneric("demonstrate")})
setMethod("demonstrate", signature = "Parzen.smoother", function(object) {
  (plot(x=object@input, y=object@Probs))
  cat("input x", object@Data, "\n")
  cat("output p(x)", object@Probs, "\n")
  cat("input for p(x)", object@input, "\n")

})

```

```{r}

 x <- matrix(0, nrow = 800, ncol = 2)
  
  # Fill the first column with random uniform values between 0 and 1
  x[, 1] <- runif(800, 0, 1)
  
  # Apply conditions on the second column based on the values in the first column
  x[x[,1] <= 0.25, 2] <- rnorm(sum(x[,1] <= 0.25), mean = 0, sd = 1)
  
  x[x[,1] > 0.25 & x[,1] <= 0.5, 2] <- rnorm(sum(x[,1] > 0.25 & x[,1] <= 0.5), mean = 3, sd = 1)
  
  x[x[,1] > 0.5 & x[,1] <= 0.75, 2] <- rnorm(sum(x[,1] > 0.5 & x[,1] <= 0.75), mean = 6, sd = 1)
    
  x[x[,1] > 0.75 & x[,1] <= 1, 2] <- rnorm(sum(x[,1] > 0.75 & x[,1] <= 1), mean = 9, sd = 1)
  
  data <- x[,2]
  
  Input <- seq(-5,10,by=.1)
  
vessel <- new("Parzen.smoother", Data = data, Probs = numeric(), input = Input, h=7)
demonstrate(Parzen.creator(vessel))


```

```{r}
# Define the true mixture of normals PDF
true_pdf <- function(x) {
  0.25 * dnorm(x, mean = 0, sd = 1) +
  0.25 * dnorm(x, mean = 3, sd = 1) +
  0.25 * dnorm(x, mean = 6, sd = 1) +
  0.25 * dnorm(x, mean = 9, sd = 1)
}



 x <- matrix(0, nrow = 800, ncol = 2)
  
  # Fill the first column with random uniform values between 0 and 1
  x[, 1] <- runif(800, 0, 1)
  
  # Apply conditions on the second column based on the values in the first column
  x[x[,1] <= 0.25, 2] <- rnorm(sum(x[,1] <= 0.25), mean = 0, sd = 1)
  
  x[x[,1] > 0.25 & x[,1] <= 0.5, 2] <- rnorm(sum(x[,1] > 0.25 & x[,1] <= 0.5), mean = 3, sd = 1)
  
  x[x[,1] > 0.5 & x[,1] <= 0.75, 2] <- rnorm(sum(x[,1] > 0.5 & x[,1] <= 0.75), mean = 6, sd = 1)
    
  x[x[,1] > 0.75 & x[,1] <= 1, 2] <- rnorm(sum(x[,1] > 0.75 & x[,1] <= 1), mean = 9, sd = 1)
  
  data <- x[,2]



# Define the input range for the plot (same as your Input in the Parzen smoother)
x_vals <- seq(-5, 10, by = 0.1)

true_pdf_values <- numeric(151)

true_pdf_values <- true_pdf(x_vals)
# Generate Parzen smoother results for different bandwidths (h values)

# h = 0.1
vessel_0.1 <- new("Parzen.smoother", Data = data, Probs = numeric(), input = Input, h = 0.1)
vessel_0.1 <- Parzen.creator(vessel_0.1)

# h = 1
vessel_1 <- new("Parzen.smoother", Data = data, Probs = numeric(), input = Input, h = 1)
vessel_1 <- Parzen.creator(vessel_1)

# h = 7
vessel_7 <- new("Parzen.smoother", Data = data, Probs = numeric(), input = Input, h = 7)
vessel_7 <- Parzen.creator(vessel_7)

# Plot the Parzen smoother KDE approximation for h = 0.1
plot(vessel_0.1@input, vessel_0.1@Probs, type = "l", col = "blue", lwd = 2,
     ylim = c(0, 0.2), main = "True Distribution vs Parzen Window Estimators",
     xlab = "x", ylab = "Density", xlim = c(-5, 10))

# Overlay the Parzen smoother KDE approximation for h = 1
lines(vessel_1@input, vessel_1@Probs, col = "green", lwd = 2)

# Overlay the Parzen smoother KDE approximation for h = 7
lines(vessel_7@input, vessel_7@Probs, col = "purple", lwd = 2)

# Add the true distribution to the same plot
lines(x_vals, true_pdf(x_vals), col = "red", lwd = 2)

# Add a legend to distinguish between the KDE estimates and the true distribution
legend("topright", legend = c("KDE h = 0.1", "KDE h = 1", "KDE h = 7", "True Distribution"),
       col = c("blue", "green", "purple", "red"), lwd = 2)

```

h=7 is clearly the best step size from the given options. 

```{r}
SAMPLE <- matrix(0, nrow = 150, ncol = 800)

for (i in 1:150) {
  
  x <- matrix(0, nrow = 800, ncol = 2)
  
  # Fill the first column with random uniform values between 0 and 1
  x[, 1] <- runif(800, 0, 1)
  
  # Apply conditions on the second column based on the values in the first column
  x[x[,1] <= 0.25, 2] <- rnorm(sum(x[,1] <= 0.25), mean = 0, sd = 1)
  x[x[,1] > 0.25 & x[,1] <= 0.5, 2] <- rnorm(sum(x[,1] > 0.25 & x[,1] <= 0.5), mean = 3, sd = 1)
  x[x[,1] > 0.5 & x[,1] <= 0.75, 2] <- rnorm(sum(x[,1] > 0.5 & x[,1] <= 0.75), mean = 6, sd = 1)
  x[x[,1] > 0.75 & x[,1] <= 1, 2] <- rnorm(sum(x[,1] > 0.75 & x[,1] <= 1), mean = 9, sd = 1)
  
  # Assign the second column (the data you need) to the SAMPLE matrix
  SAMPLE[i,] <- x[, 2]
}
```


```{r}
table_of_evaluations_at_trials <- matrix(0,nrow=150,ncol=151)

for (i in 1:150) {
  
vessel_phi <- new("Parzen.smoother", Data = SAMPLE[i,], Probs = numeric(), input = Input, h = 7)
vessel_phi <- Parzen.creator(vessel_phi)

table_of_evaluations_at_trials[i,] <- vessel_phi@Probs

}



sample_evaluated <- table_of_evaluations_at_trials

column_names <- seq(-5, 10, by = 0.1)

colnames(sample_evaluated) <- column_names

rows <- seq(1:150)

rownames(sample_evaluated) <- rows

mean_for_each_alpha <- matrix(0, nrow = 1, ncol = 151)
mean_for_each_alpha[1, ] <- colMeans(sample_evaluated[, seq(1:151)])
(mean_for_each_alpha)

plot(x=column_names, y=mean_for_each_alpha)

```


```{r}
variance_for_each_alpha <- matrix(0,nrow=1,ncol=151)
for(i in 1:151){
    variance_for_each_alpha[1,i] <- mean((sample_evaluated[seq(1:150),i]-mean_for_each_alpha[1,i])^2)
}




bias <- matrix(0,nrow=1,ncol=151)
for (i in 1:151) {
  bias[1,i] <- mean_for_each_alpha[1,i] - true_pdf_values[i]
}



MSE <- numeric(151)
for (i in 1:151) {
  MSE[i] <- variance_for_each_alpha[1,i] + (bias[i])^2
}



bias_totall <- numeric(1)
for (i in 1:151)
bias_totall <- mean((bias[i])^2)



var_totall <- numeric(1)
for (i in 1:151)
var_totall <- mean((variance_for_each_alpha[i]))



print(bias_totall)
print(var_totall)
```


```{r}
h<- c(.01, .1, .3, .6, 1, 3, 7)

bias_column <- c(0.01549748,0.0003584315,3.234368e-05,1.273845e-08,4.866585e-06,0.0001553659,0.0004310315)
var_column <- c(5.100354,0.1145063,0.0457739,0.02382282,0.01360701,0.00249561,0.0002015679 )

data <- data.frame(h, bias_column, var_column)
plot(data$h, data$bias_column, type="b", col="blue", 
     xlab="h", ylab="Value", main="Bias and Variance as a function of h")
lines(data$h, data$var_column, type="b", col="red")

MSE <- data[,2] + data[,3]


(h[which.min(MSE)])

#ONCE AGAIN IT'S SEVEN, THE RESULT IS CONFIRMED

```




